### ISSUE TITLE
Free Hosting

### ISSUE THREAD

**Issue by mhinterdorfer** [rstropek-teaching/real-time-game-quiz-4ahif-MHinterdorfer#2]
I want to implement a REST-API for my Highscore-List. 
Do you know any free hosting platform for the API and the game-server?

**Comment by rstropek** [comment]
Hi @MHinterdorfer 

I recommend [Azure App Service](https://azure.microsoft.com/en-us/services/app-service/). It works [very well with Node.js](https://docs.microsoft.com/en-us/azure/app-service/app-service-deploy-local-git). It is [free](https://azure.microsoft.com/en-us/offers/ms-azr-0144p/) for students.

Does this help?

Greetings,
Rainer Stropek.

**Comment by mhinterdorfer** [comment]
I will give it a try!

Thanks for your help,
Michael Hinterdorfer

**Comment by mhinterdorfer** [comment]
I have tried to use Azure, but it doesn't work.
I was able to log in and to enter the Azure Portal but when I try to create a new service I get passed on to the registration page.

Do you know how to handle this?

Greetings,
Michael Hinterdorfer

**Comment by rstropek** [comment]
Hi @MHinterdorfer 

You do not need a credit card for Azure if you use your [Microsoft Imagine](https://imagine.microsoft.com/en-us/Catalog/Product/99) account. Otherwise, a credit card is required.

If you do not have an Imagine account, tell me. In that case, I can offer you a time-limited Azure Web app for free from our programming club. We have some Azure credits that we can use for such purposes.

Greetings,
Rainer Stropek.
